service:
  name: ${env:NAME}
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  timeout: 90
  runtime: nodejs14.x
  stage: ${env:STAGE}
  region: ${env:REGION}
  versionFunctions: false
  apiKeys:
    - free:
        - myFreeApiKey
    - paid:
        - highliy-confidential
  usagePlan:
    - free:
        quota:
          limit: 2
          peiod: DAY
        throttle:
          rateLimit: 1
          burstLimit: 5
    - paid:
        quota:
          limit: 10
          period: DAY
        throttle:
          rateLimit: 5
          burstLimit: 10
package:
  individually: true
custom:
  urlPrefix: 'sls'
  serverless-offline:
    apiKey: 'confidential'
  webpack:
    includeModules: true
    excludeFiles: ./**/*.test.js
functions: ${file(./resources/lambda/functions.yml)}
resources:
  - ${file(./resources/config/iam.yml)}
