export const mockData = {
	MOCK_ORGANIZATION: { Organization: 'wednesday-solutions' },
	MOCK_ORGANIZATION_SUCCESS_RESPONSE: {
		data: {
			login: 'wednesday-solutions',
			id: 50692559,
			node_id: 'MDEyOk9yZ2FuaXphdGlvbjUwNjkyNTU5',
			url: 'https://api.github.com/orgs/wednesday-solutions',
			repos_url: 'https://api.github.com/orgs/wednesday-solutions/repos',
			events_url: 'https://api.github.com/orgs/wednesday-solutions/events',
			hooks_url: 'https://api.github.com/orgs/wednesday-solutions/hooks',
			issues_url: 'https://api.github.com/orgs/wednesday-solutions/issues',
			members_url:
				'https://api.github.com/orgs/wednesday-solutions/members{/member}',
			public_members_url:
				'https://api.github.com/orgs/wednesday-solutions/public_members{/member}',
			avatar_url: 'https://avatars.githubusercontent.com/u/50692559?v=4',
			description: '',
			name: 'Wednesday',
			company: null,
			blog: 'https://wednesday.is',
			location: 'Pune',
			email: 'hello@wednesday.is',
			twitter_username: 'wednesdaysol',
			is_verified: false,
			has_organization_projects: true,
			has_repository_projects: true,
			public_repos: 51,
			public_gists: 0,
			followers: 0,
			following: 0,
			html_url: 'https://github.com/wednesday-solutions',
			created_at: '2019-05-16T06:16:40Z',
			updated_at: '2022-03-14T09:44:48Z',
			type: 'Organization',
		},
	},
	MOCK_ORGANIZATION_FAILURE_RESPONSE: {
		errorCode: 500,
		errMessage: 'Request failed with status code 404',
	},
	MOCK_MEME_SUCCESS_RESPONSE: {
		code: 200,
		data: [
			{
				ID: 1,
				bottomText: 'Good!',
				image: 'http://imgflip.com/s/meme/Grumpy-Cat.jpg',
				name: 'Grumpy Cat',
				rank: 10,
				tags: 'Tardar Sauce, Tabatha Bundesen, Felis domesticus',
				topText: '',
			},
			{
				ID: 7,
				bottomText: 'Winter is Coming',
				image: 'https://imgflip.com/s/meme/Brace-Yourselves-X-is-Coming.jpg',
				name: 'Brace Yourselves',
				rank: 20,
				tags:
					'Winter is Coming, Ned Stark, Sean Bean, Game of Thrones, GOT, Imminent Ned',
				topText: 'Brace Yourselves',
			},
			{
				ID: 3,
				bottomText: 'Or just ___',
				image: 'https://imgflip.com/s/meme/Futurama-Fry.jpg',
				name: 'Futurama Fry',
				rank: 30,
				tags: 'Not Sure If',
				topText: 'Not sure if ___',
			},
			{
				ID: 5,
				bottomText: 'Walk into mordor',
				image: 'https://imgflip.com/s/meme/One-Does-Not-Simply.jpg',
				name: 'One Does Not Simply',
				rank: 40,
				tags:
					'One Does Not Simply Walk Into Mordor, Boromir, Sean Bean, Ned Stark, LOTR, Lord of the rings, One Ring',
				topText: 'One does not simply',
			},
			{
				ID: 4,
				bottomText: null,
				image: 'https://imgflip.com/s/meme/Bad-Luck-Brian.jpg',
				name: 'Bad Luck Brian',
				rank: 50,
				tags: 'Bad Luck Kyle',
				topText: null,
			},
			{
				ID: 6,
				bottomText: null,
				image: 'https://imgflip.com/s/meme/First-World-Problems.jpg',
				name: 'First World Problems',
				rank: 60,
				tags: 'Crying, FWP, White Whine',
				topText: null,
			},
			{
				ID: 2,
				bottomText: 'Who ___',
				image: 'https://imgflip.com/s/meme/Am-I-The-Only-One-Around-Here.jpg',
				name: 'Am I The Only One Around Here',
				rank: 70,
				tags: 'Dude Abides, Big Lebowski, Angry Walter Sobchak',
				topText: 'Am I the only one around here',
			},
			{
				ID: 8,
				bottomText: 'Success!',
				image: 'https://imgflip.com/s/meme/Success-Kid.jpg',
				name: 'Success Kid',
				rank: 80,
				tags: 'I hate sandcastles, eating sand',
				topText: null,
			},
			{
				ID: 9,
				bottomText: null,
				image: 'https://imgflip.com/s/meme/Awkward-Moment-Sealion.jpg',
				name: 'Awkward Moment Seal',
				rank: 90,
				tags: 'Poker Face',
				topText: null,
			},
			{
				ID: 10,
				bottomText: null,
				image: 'https://imgflip.com/s/meme/Confession-Bear.jpg',
				name: 'Confession Bear',
				rank: 100,
				tags: 'Animal, Advice',
				topText: null,
			},
			{
				ID: 15,
				bottomText: 'Enough!',
				image: 'https://imgflip.com/s/meme/Batman-Slapping-Robin.jpg',
				name: 'Batman Slapping Robin',
				rank: 110,
				tags: 'My parents are dead',
				topText: '',
			},
			{
				ID: 16,
				bottomText: '',
				image: 'https://imgflip.com/s/meme/Grandma-Finds-The-Internet.jpg',
				name: 'Grandma Finds the Internet',
				rank: 120,
				tags: 'Internet Grandma Surprise',
				topText: '',
			},
			{
				ID: 11,
				bottomText: '"Aliens"',
				image: 'https://imgflip.com/s/meme/Ancient-Aliens.jpg',
				name: 'Ancient Aliens',
				rank: 130,
				tags: 'History Channel Guy, Giorgio A Tsoukalos',
				topText: '',
			},
			{
				ID: 14,
				bottomText: '',
				image: 'https://imgflip.com/s/meme/Creepy-Condescending-Wonka.jpg',
				name: 'Condescending Wonka',
				rank: 140,
				tags:
					'Creepy WIlly Wonka, Willy wonka and the chocolate factory, Gene Wilder',
				topText: '',
			},
			{
				ID: 12,
				bottomText: '',
				image: 'https://imgflip.com/s/meme/Actual-Advice-Mallard.jpg',
				name: 'Actual Advice Mallard',
				rank: 150,
				tags: 'Green, Duck, Advice',
				topText: '',
			},
			{
				ID: 13,
				bottomText: 'But when I do ___',
				image:
					'https://imgflip.com/s/meme/The-Most-Interesting-Man-In-The-World.jpg',
				name: 'The Most Interesting Man in the World',
				rank: 160,
				tags: 'Jonathan Goldsmith',
				topText: "I don't always ___",
			},
			{
				ID: 56,
				bottomText: '',
				image: 'https://imgflip.com/s/meme/Philosoraptor.jpg',
				name: 'Philosoraptor',
				rank: 165,
				tags: 'What if, dinosaur, Velociraptor, metaphysical inquiries',
				topText: 'What if ...',
			},
			{
				ID: 17,
				bottomText: 'Everywhere',
				image: 'https://imgflip.com/s/meme/X-Everywhere.jpg',
				name: 'X, X Everywhere',
				rank: 170,
				tags: 'Toy story, Buzz lightyear, Woody',
				topText: '___, ___',
			},
			{
				ID: 20,
				bottomText: "That'd be great",
				image: 'https://imgflip.com/s/meme/That-Would-Be-Great.jpg',
				name: 'That would be great',
				rank: 180,
				tags: 'Bill Lumbergh, Office Space',
				topText: 'Yeah, If you could just ___',
			},
			{
				ID: 18,
				bottomText: '',
				image: 'https://imgflip.com/s/meme/Good-Guy-Greg.jpg',
				name: 'Good Guy Greg',
				rank: 180,
				tags: 'ggg',
				topText: '      ',
			},
			{
				ID: 258,
				bottomText: 'Show Me What You Got',
				image: 'http://i.imgur.com/6Ln3hp8.png',
				name: 'Show Me What You Got',
				rank: 188,
				tags: 'Rick and Morty, Giant Heads, Dan, Justin, Adult Swim',
				topText: '',
			},
			{
				ID: 21,
				bottomText: '',
				image: 'https://imgflip.com/readImage?iid=21808196',
				name: 'What if I told you',
				rank: 200,
				tags: 'Matrix, Morpheus, Lawrence Fishburne',
				topText: 'What if I Told You',
			},
			{
				ID: 55,
				bottomText: "Ain't nobody got time for that",
				image: 'https://imgflip.com/s/meme/Aint-Nobody-Got-Time-For-That.jpg',
				name: "Ain't nobody got time for that",
				rank: 205,
				tags: 'sweet brown Kimberly Wilkins',
				topText: '',
			},
			{
				ID: 54,
				bottomText: '',
				image: 'https://imgflip.com/s/meme/Insanity-Wolf.jpg',
				name: 'Insanity Wolf',
				rank: 205,
				tags: 'animal, insane, dog',
				topText: '',
			},
		],
		message: 'GET successful',
		next: 'http://alpha-meme-maker.herokuapp.com/2',
	},
	MOCK_MEME__FAILURE_RESPONSE: {
		errorCode: 500,
		errMessage: 'ValidationError: "page" must be a number',
	},
	MOCK_JOKE_SUCCESS_RESPONSE: {
		error: false,
		category: 'Programming',
		type: 'twopart',
		setup: 'Why did the web developer walk out of a resturant in disgust?',
		delivery: 'The seating was laid out in tables.',
		flags: {
			nsfw: false,
			religious: false,
			political: false,
			racist: false,
			sexist: false,
			explicit: false,
		},
		id: 6,
		safe: true,
		lang: 'en',
	},
	MOCK_JOKE_FAILURE_RESPONSE: {
		error: true,
		internalError: false,
		code: 106,
		message: 'No matching joke found',
		causedBy: ['No jokes were found that match your provided filter(s).'],
		additionalInfo:
			"The specified category/ies is/are invalid. Got: 'progra' but possible categories are: Any, Misc, Programming, Dark, Pun, Spooky, Christmas (case insensitive).",
		timestamp: 1647853231189,
	},
};
